name: flutter_dep_matrix
description: "Command line tool for aggregating dependencies from multiple packages and displaying the 
dependencies as a matrix."
version: 0.0.2+2
repository: git@github.com:tmcmaster/flutter_dep_matrix.git

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  args: ^2.7.0
  yaml: ^3.1.3
  path: ^1.9.1
  process_run: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

executables:
  flutter_dep_matrix: flutter_dep_matrix
